export const servicesMobile = [
    {
      productImage: "/mini.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Mini Boom",
      BoomArmLength: "15-17 Meter",
      NoOfArms: "4 Section Boom",
      CarLength: "7 meters",
      CarHeight: "2.8 meters",
      CarWidth: "2.4 meters",
      CarWeight: "10 tons",
      Jacking: "4 Meters (Front), 4 Meters (Rear)",
    },
    {
      productImage: "/Semi long Boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Semi Long Boom",
      BoomArmLength: "18-21 Meter",
      CarLength: "7 meters",
      CarHeight: "2.8 meters",
      CarWidth: "2.4 meters",
      CarWeight: "10 tons",
      Jacking: "4 Meters (Front), 4 Meters (Rear)",
    },
    {
      productImage: "/standard.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Standard Boom",
      BoomArmLength: "24 Meter",
      NoOfArms: "4 Section Boom",
      CarLength: "9.2 meters",
      CarHeight: "3.3 meters",
      CarWidth: "2.5 meters",
      CarWeight: "14 tons",
      Jacking: "4 Meters (Front), 4 Meters (Rear)",
    },
    {
      productImage: "/long boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Long Boom",
      BoomArmLength: "26 Meter",
      CarLength: "9.2 meters",
      CarHeight: "3.5 meters",
      CarWidth: "2.5 meters",
      CarWeight: "14 tons",
      Jacking: "4.2 Meters (Front), 3.9 Meters (Rear)",
    },
    {
      productImage: "/super long boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Super Long Boom",
      BoomArmLength: "27-30 Meter",
      NoOfArms: "4 Section Boom",
      CarLength: "12 meters",
      CarHeight: "3.5 meters",
      CarWidth: "2.5 meters",
      CarWeight: "18 tons",
      Jacking: "6.3 Meters (Front), 4 Meters (Rear)",
    },
    {
      productImage: "/Double super long boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Double Super Long Boom",
      BoomArmLength: "33-36 Meter",
      NoOfArms: "4 Section Boom",
      CarLength: "11 meters",
      CarHeight: "4 meters",
      CarWidth: "3 meters",
      CarWeight: "24 tons",
      Jacking: "5.2 meters",
    },
    {
      productImage: "/Extra Doble Super Long Boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Extra Double Super Long Boom",
      BoomArmLength: "37-40 Meter",
      NoOfArms: "4/5 Section Boom",
      CarLength: "12 meters",
      CarHeight: "4 meters",
      CarWidth: "2.5 meters",
      CarWeight: "34 tons",
      Jacking: "8.3 meters",
    },
    {
      productImage: "/Extra Doble Super Long Boom.png",
      productName: "Mobile Concrete Pump",
      ToolsType: "Extra Double Super Long Boom",
      BoomArmLength: "41-60 Meter",
      NoOfArms: "5/6 Section Boom",
      CarLength: "15 meters",
      CarHeight: "4 meters",
      CarWidth: "2.5 meters",
      CarWeight: "53 tons",
      Jacking: "5.7 Meters (Front), 6.3 Meters (Rear)",
    },
  ];
  